# Sample hypinput.ini
# All key options listed
# Hypseus uses SDL3 Keycodes
#
# Hypseus Singe supports configuration on multiple joysticks
#
# IMPORTANT: Finding joystick button and axis:
#
# Use the 'hypjsch' tools to help configure this file
# https://github.com/DirtBagXon/hypjsch


# KEY_BUTTON3 Turns scoreboard on/off in lair/ace

#                 Key1            Key2         Button    (Axis)
[KEYBOARD]
KEY_UP          = SDLK_UP         0            0          -002
KEY_DOWN        = SDLK_DOWN       0            0          +002
KEY_LEFT        = SDLK_LEFT       0            0          -001
KEY_RIGHT       = SDLK_RIGHT      0            0          +001
KEY_COIN1       = SDLK_5          0            0
KEY_COIN2       = SDLK_6          0            0
KEY_START1      = SDLK_1          0            0
KEY_START2      = SDLK_2          0            0
KEY_BUTTON1     = SDLK_LCTRL      0            0
KEY_BUTTON2     = SDLK_LALT       0            0
KEY_BUTTON3     = SDLK_SPACE      0            0
KEY_SKILL1      = SDLK_LSHIFT     0            0
KEY_SKILL2      = SDLK_Z          0            0
KEY_SKILL3      = SDLK_X          0            0
KEY_SERVICE     = SDLK_9          0            0
KEY_TEST        = SDLK_F2         SDLK_F4      0
KEY_RESET       = SDLK_0          0            0
KEY_SCREENSHOT  = SDLK_F12        0            0
KEY_QUIT        = SDLK_ESCAPE     0            0
KEY_PAUSE       = SDLK_P          0            0
KEY_CONSOLE     = SDLK_BACKSLASH  0            0
KEY_TILT        = SDLK_T          0            0
END

[MOUSE]
MOUSE_BUTTON1   = KEY_BUTTON3
MOUSE_BUTTON2   = KEY_BUTTON1
MOUSE_BUTTON3   = KEY_BUTTON2
END

# [GLOBAL] options will override command-line arguments.
# This section is optional. It can safely be removed entirely,
# or any non-required options discarded.
# Remove # to enable an option.

[GLOBAL]
SCREEN          = 0
VLDPVOLUME      = 40
NONVLDPVOLUME   = 10
SOUNDBUFFER     = 2048
#ALWAYSONTOP    = FALSE
FULLSCREEN      = FALSE
#MANYMOUSE      = TRUE
GAMEPAD         = FALSE
#SCANLINES      = FALSE
GRAPHICAPI      = AUTO
END

# Valid GRAPHICAPI: OPENGL | VULKAN | AUTO
