/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_setup_window (void);
GtkWidget* create_dl_window (void);
GtkWidget* create_ldp_window (void);
GtkWidget* create_tq_window (void);
GtkWidget* create_sdq_window (void);
GtkWidget* create_fileselection1 (void);
GtkWidget* create_cliff_window (void);
GtkWidget* create_no_config_dialog (void);
