/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
//#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_setup_window (void)
{
  GtkWidget *setup_window;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *label5;
  GtkWidget *vbox2;
  GtkWidget *game_option_menu;
  GtkWidget *game_option_menu_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *config_game_button;
  GtkWidget *label2;
  GtkWidget *pixmap1;
  GtkWidget *hseparator1;
  GtkWidget *hbox2;
  GtkWidget *label6;
  GtkWidget *vbox3;
  GtkWidget *ldp_option_menu;
  GtkWidget *ldp_option_menu_menu;
  GtkWidget *config_ldp_button;
  GtkWidget *label4;
  GtkWidget *pixmap2;
  GtkWidget *hseparator2;
  GtkWidget *hbox3;
  GtkWidget *label7;
  GtkWidget *start_daphne_button;
  GtkWidget *vbox4;
  GtkWidget *load_config_button;
  GtkWidget *save_config_button;
  GtkWidget *reset_defaults_button;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  setup_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (setup_window), "setup_window", setup_window);
  gtk_container_set_border_width (GTK_CONTAINER (setup_window), 10);
  gtk_window_set_title (GTK_WINDOW (setup_window), _("DAPHNE Setup"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (setup_window), vbox1);

  hbox1 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  label5 = gtk_label_new (_("Step 1:\nChoose which game\nyou want to play."));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);

  vbox2 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, TRUE, TRUE, 0);

  game_option_menu = gtk_option_menu_new ();
  gtk_widget_ref (game_option_menu);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "game_option_menu", game_option_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (game_option_menu);
  gtk_box_pack_start (GTK_BOX (vbox2), game_option_menu, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, game_option_menu, _("Choose the game you want to play from this list.  You can also test the seek speed of your laserdisc player by choosing the Speed Test."), NULL);
  game_option_menu_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Cliff Hanger"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (game_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Dragon's Lair"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (game_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Dragon's Lair Enhanced"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (game_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Space Ace"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (game_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Speed Test"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (game_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Super Don Quix-ote"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (game_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Thayer's Quest"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (game_option_menu_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (game_option_menu), game_option_menu_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (game_option_menu), 1);

  config_game_button = gtk_button_new_with_label (_("Configure Game"));
  gtk_widget_ref (config_game_button);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "config_game_button", config_game_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (config_game_button);
  gtk_box_pack_start (GTK_BOX (vbox2), config_game_button, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Status: OK"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox2), label2, FALSE, FALSE, 0);

  pixmap1 = create_pixmap (setup_window, "bonk.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (hbox1), pixmap1, TRUE, TRUE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Step 2:\nChoose which laserdisc\nplayer you want to use."));
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  vbox3 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox3, TRUE, TRUE, 0);

  ldp_option_menu = gtk_option_menu_new ();
  gtk_widget_ref (ldp_option_menu);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "ldp_option_menu", ldp_option_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ldp_option_menu);
  gtk_box_pack_start (GTK_BOX (vbox3), ldp_option_menu, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, ldp_option_menu, _("Choose your laserdisc player's type from this list.  Choose mpeg1 if you want to use an mpeg1 dump of a laserdisc instead of a real laserdisc."), NULL);
  ldp_option_menu_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("No Laserdisc Player"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Hitachi VIP-9550"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("MPEG1 Virtual Laserdisc"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Pioneer Common"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Pioneer LD-V6000's"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_option_menu_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Sony"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_option_menu_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (ldp_option_menu), ldp_option_menu_menu);

  config_ldp_button = gtk_button_new_with_label (_("Configure Laserdisc Player"));
  gtk_widget_ref (config_ldp_button);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "config_ldp_button", config_ldp_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (config_ldp_button);
  gtk_box_pack_start (GTK_BOX (vbox3), config_ldp_button, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("Status: OK"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox3), label4, FALSE, FALSE, 0);

  pixmap2 = create_pixmap (setup_window, "disc.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_box_pack_start (GTK_BOX (hbox2), pixmap2, TRUE, TRUE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator2, TRUE, TRUE, 0);

  hbox3 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, TRUE, TRUE, 0);

  label7 = gtk_label_new (_("Step 3:"));
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  start_daphne_button = gtk_button_new_with_label (_("Start DAPHNE!"));
  gtk_widget_ref (start_daphne_button);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "start_daphne_button", start_daphne_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (start_daphne_button);
  gtk_box_pack_start (GTK_BOX (hbox3), start_daphne_button, FALSE, TRUE, 0);

  vbox4 = gtk_vbox_new (TRUE, 5);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox3), vbox4, TRUE, TRUE, 0);

  load_config_button = gtk_button_new_with_label (_("Load Config"));
  gtk_widget_ref (load_config_button);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "load_config_button", load_config_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load_config_button);
  gtk_box_pack_start (GTK_BOX (vbox4), load_config_button, FALSE, FALSE, 0);

  save_config_button = gtk_button_new_with_label (_("Save Config"));
  gtk_widget_ref (save_config_button);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "save_config_button", save_config_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save_config_button);
  gtk_box_pack_start (GTK_BOX (vbox4), save_config_button, FALSE, FALSE, 0);

  reset_defaults_button = gtk_button_new_with_label (_("Reset to Defaults"));
  gtk_widget_ref (reset_defaults_button);
  gtk_object_set_data_full (GTK_OBJECT (setup_window), "reset_defaults_button", reset_defaults_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (reset_defaults_button);
  gtk_box_pack_start (GTK_BOX (vbox4), reset_defaults_button, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (setup_window), "destroy",
                      GTK_SIGNAL_FUNC (on_setup_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (config_game_button), "clicked",
                      GTK_SIGNAL_FUNC (configure_game),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (config_ldp_button), "clicked",
                      GTK_SIGNAL_FUNC (configure_ldp),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (start_daphne_button), "clicked",
                      GTK_SIGNAL_FUNC (startdaphne),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load_config_button), "clicked",
                      GTK_SIGNAL_FUNC (on_load_config_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save_config_button), "clicked",
                      GTK_SIGNAL_FUNC (on_save_config_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (reset_defaults_button), "clicked",
                      GTK_SIGNAL_FUNC (on_reset_defaults_button_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (setup_window), "tooltips", tooltips);

  return setup_window;
}

GtkWidget*
create_dl_window (void)
{
  GtkWidget *dl_window;
  GtkWidget *vbox5;
  GtkWidget *label8;
  GtkWidget *hbox4;
  GtkWidget *label9;
  GtkWidget *dl_rom_names;
  GtkWidget *hbox5;
  GtkWidget *label10;
  GtkWidget *dl_difficulty;
  GtkWidget *dl_difficulty_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *hbox6;
  GtkWidget *label11;
  GtkWidget *dl_lives;
  GtkWidget *dl_lives_menu;
  GtkWidget *hbox15;
  GtkWidget *label47;
  GtkWidget *dl_audio;
  GtkWidget *dl_audio_menu;
  GtkWidget *hbox8;
  GtkWidget *label12;
  GtkWidget *dl_cost;
  GtkWidget *dl_cost_menu;
  GtkWidget *hbox9;
  GtkWidget *label13;
  GtkWidget *dl_scoreboard;
  GtkWidget *dl_scoreboard_menu;
  GtkWidget *hbox10;
  GtkWidget *label14;
  GtkWidget *dl_disc;
  GtkWidget *dl_disc_menu;
  GtkWidget *hseparator3;
  GtkWidget *hbox11;
  guint dl_ok_key;
  GtkWidget *dl_ok;
  guint dl_cancel_key;
  GtkWidget *dl_cancel;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  dl_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (dl_window), "dl_window", dl_window);
  gtk_container_set_border_width (GTK_CONTAINER (dl_window), 10);
  gtk_window_set_title (GTK_WINDOW (dl_window), _("Dragon's Lair Configuration"));

  vbox5 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (dl_window), vbox5);

  label8 = gtk_label_new (_("Description: Dragon's Lair, NTSC Version, Revision F2 ROMS"));
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (vbox5), label8, FALSE, TRUE, 0);

  hbox4 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox4, FALSE, TRUE, 0);

  label9 = gtk_label_new (_("ROM names"));
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  dl_rom_names = gtk_label_new (_("name1.bin, name2.bin, etc."));
  gtk_widget_ref (dl_rom_names);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_rom_names", dl_rom_names,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_rom_names);
  gtk_box_pack_start (GTK_BOX (hbox4), dl_rom_names, FALSE, FALSE, 0);

  hbox5 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox5, FALSE, TRUE, 0);

  label10 = gtk_label_new (_("Difficulty"));
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  dl_difficulty = gtk_option_menu_new ();
  gtk_widget_ref (dl_difficulty);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_difficulty", dl_difficulty,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_difficulty);
  gtk_box_pack_start (GTK_BOX (hbox5), dl_difficulty, FALSE, TRUE, 0);
  dl_difficulty_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Easy"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Hard"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Very Hard"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_difficulty_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (dl_difficulty), dl_difficulty_menu);

  hbox6 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox6, FALSE, TRUE, 0);

  label11 = gtk_label_new (_("Lives"));
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox6), label11, FALSE, FALSE, 0);

  dl_lives = gtk_option_menu_new ();
  gtk_widget_ref (dl_lives);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_lives", dl_lives,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_lives);
  gtk_box_pack_start (GTK_BOX (hbox6), dl_lives, FALSE, TRUE, 0);
  dl_lives_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Three"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Five"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Unlimited"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_lives_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (dl_lives), dl_lives_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (dl_lives), 1);

  hbox15 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox15);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox15", hbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox15, TRUE, TRUE, 0);

  label47 = gtk_label_new (_("Attract mode audio"));
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox15), label47, FALSE, FALSE, 0);

  dl_audio = gtk_option_menu_new ();
  gtk_widget_ref (dl_audio);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_audio", dl_audio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_audio);
  gtk_box_pack_start (GTK_BOX (hbox15), dl_audio, FALSE, TRUE, 0);
  dl_audio_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Always On"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_audio_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Always Off"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_audio_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("On every eighth time"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_audio_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (dl_audio), dl_audio_menu);

  hbox8 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox8, TRUE, TRUE, 0);

  label12 = gtk_label_new (_("One credit costs"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox8), label12, FALSE, FALSE, 0);

  dl_cost = gtk_option_menu_new ();
  gtk_widget_ref (dl_cost);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_cost", dl_cost,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_cost);
  gtk_box_pack_start (GTK_BOX (hbox8), dl_cost, FALSE, TRUE, 0);
  dl_cost_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Two Coins"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Three Coins"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_cost_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (dl_cost), dl_cost_menu);

  hbox9 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox9);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox9, TRUE, TRUE, 0);

  label13 = gtk_label_new (_("External Scoreboard"));
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox9), label13, FALSE, FALSE, 0);

  dl_scoreboard = gtk_option_menu_new ();
  gtk_widget_ref (dl_scoreboard);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_scoreboard", dl_scoreboard,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_scoreboard);
  gtk_box_pack_start (GTK_BOX (hbox9), dl_scoreboard, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, dl_scoreboard, _("If you have a real Dragon's Lair scoreboard, DAPHNE can control it via a parallel port."), NULL);
  dl_scoreboard_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("None"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_scoreboard_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("LPT1"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_scoreboard_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("LPT2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_scoreboard_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (dl_scoreboard), dl_scoreboard_menu);

  hbox10 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox10);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox10", hbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox10, TRUE, TRUE, 0);

  label14 = gtk_label_new (_("Laserdisc"));
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox10), label14, FALSE, FALSE, 0);

  dl_disc = gtk_option_menu_new ();
  gtk_widget_ref (dl_disc);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_disc", dl_disc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_disc);
  gtk_box_pack_start (GTK_BOX (hbox10), dl_disc, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, dl_disc, _("USA/Canadian discs are NTSC, which is what the ROMs were designed to use.  DAPHNE can also use European PAL discs, as well as the (unauthorized?) Software Corner PAL discs."), NULL);
  dl_disc_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("USA/Canadian"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_disc_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("European"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_disc_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Software Corner"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (dl_disc_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (dl_disc), dl_disc_menu);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator3);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hseparator3", hseparator3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox5), hseparator3, TRUE, TRUE, 0);

  hbox11 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox11);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "hbox11", hbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox11, FALSE, FALSE, 0);

  dl_ok = gtk_button_new_with_label ("");
  dl_ok_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (dl_ok)->child),
                                   _("_OK"));
  gtk_widget_add_accelerator (dl_ok, "clicked", accel_group,
                              dl_ok_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (dl_ok);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_ok", dl_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_ok);
  gtk_box_pack_start (GTK_BOX (hbox11), dl_ok, FALSE, TRUE, 0);

  dl_cancel = gtk_button_new_with_label ("");
  dl_cancel_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (dl_cancel)->child),
                                   _("_Cancel"));
  gtk_widget_add_accelerator (dl_cancel, "clicked", accel_group,
                              dl_cancel_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (dl_cancel);
  gtk_object_set_data_full (GTK_OBJECT (dl_window), "dl_cancel", dl_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dl_cancel);
  gtk_box_pack_start (GTK_BOX (hbox11), dl_cancel, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (dl_window), "destroy",
                      GTK_SIGNAL_FUNC (on_dl_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dl_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_dl_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dl_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_dl_cancel_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (dl_window), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (dl_window), accel_group);

  return dl_window;
}

GtkWidget*
create_ldp_window (void)
{
  GtkWidget *ldp_window;
  GtkWidget *table1;
  GtkWidget *label15;
  GtkWidget *label16;
  guint ldp_ok_key;
  GtkWidget *ldp_ok;
  guint ldp_cancel_key;
  GtkWidget *ldp_cancel;
  GtkWidget *ldp_port;
  GtkWidget *ldp_port_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *ldp_speed;
  GtkWidget *ldp_speed_menu;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  ldp_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (ldp_window), "ldp_window", ldp_window);
  gtk_window_set_title (GTK_WINDOW (ldp_window), _("LDP Configuration"));

  table1 = gtk_table_new (3, 2, TRUE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (ldp_window), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (ldp_window), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 10);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  label15 = gtk_label_new (_("Serial Port"));
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (ldp_window), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table1), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label16 = gtk_label_new (_("Serial Port Speed"));
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (ldp_window), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table1), label16, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  ldp_ok = gtk_button_new_with_label ("");
  ldp_ok_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (ldp_ok)->child),
                                   _("_OK"));
  gtk_widget_add_accelerator (ldp_ok, "clicked", accel_group,
                              ldp_ok_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (ldp_ok);
  gtk_object_set_data_full (GTK_OBJECT (ldp_window), "ldp_ok", ldp_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ldp_ok);
  gtk_table_attach (GTK_TABLE (table1), ldp_ok, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);

  ldp_cancel = gtk_button_new_with_label ("");
  ldp_cancel_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (ldp_cancel)->child),
                                   _("_Cancel"));
  gtk_widget_add_accelerator (ldp_cancel, "clicked", accel_group,
                              ldp_cancel_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (ldp_cancel);
  gtk_object_set_data_full (GTK_OBJECT (ldp_window), "ldp_cancel", ldp_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ldp_cancel);
  gtk_table_attach (GTK_TABLE (table1), ldp_cancel, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);

  ldp_port = gtk_option_menu_new ();
  gtk_widget_ref (ldp_port);
  gtk_object_set_data_full (GTK_OBJECT (ldp_window), "ldp_port", ldp_port,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ldp_port);
  gtk_table_attach (GTK_TABLE (table1), ldp_port, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  ldp_port_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("COM1"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_port_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("COM2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_port_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (ldp_port), ldp_port_menu);

  ldp_speed = gtk_option_menu_new ();
  gtk_widget_ref (ldp_speed);
  gtk_object_set_data_full (GTK_OBJECT (ldp_window), "ldp_speed", ldp_speed,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ldp_speed);
  gtk_table_attach (GTK_TABLE (table1), ldp_speed, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  ldp_speed_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("4800"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_speed_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("9600"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (ldp_speed_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (ldp_speed), ldp_speed_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (ldp_speed), 1);

  gtk_signal_connect (GTK_OBJECT (ldp_window), "destroy",
                      GTK_SIGNAL_FUNC (on_ldp_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ldp_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_ldp_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ldp_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_ldp_cancel_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (ldp_window), accel_group);

  return ldp_window;
}

GtkWidget*
create_tq_window (void)
{
  GtkWidget *tq_window;
  GtkWidget *vbox6;
  GtkWidget *label21;
  GtkWidget *hseparator5;
  GtkWidget *table3;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *tq_time;
  GtkWidget *tq_time_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *tq_cost;
  GtkWidget *tq_cost_menu;
  GtkWidget *tq_audio;
  GtkWidget *tq_audio_menu;
  GtkWidget *label22;
  GtkWidget *tq_lives;
  GtkWidget *tq_lives_menu;
  GtkWidget *label17;
  GtkWidget *tq_rom_names;
  GtkWidget *label24;
  GtkWidget *tq_scoreboard;
  GtkWidget *tq_scoreboard_menu;
  GtkWidget *hseparator4;
  GtkWidget *hbox12;
  guint tq_ok_key;
  GtkWidget *tq_ok;
  guint tq_cancel_key;
  GtkWidget *tq_cancel;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  tq_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (tq_window), "tq_window", tq_window);
  gtk_window_set_title (GTK_WINDOW (tq_window), _("Thayer's Quest Configuration"));

  vbox6 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (tq_window), vbox6);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 10);

  label21 = gtk_label_new (_("Description: Thayer's Quest, NTSC version"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (vbox6), label21, FALSE, FALSE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator5);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "hseparator5", hseparator5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator5, TRUE, TRUE, 0);

  table3 = gtk_table_new (6, 2, TRUE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox6), table3, TRUE, TRUE, 0);

  label18 = gtk_label_new (_("Time per credit"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table3), label18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("One credit costs"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table3), label19, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label20 = gtk_label_new (_("Attract mode audio"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table3), label20, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  tq_time = gtk_option_menu_new ();
  gtk_widget_ref (tq_time);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_time", tq_time,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_time);
  gtk_table_attach (GTK_TABLE (table3), tq_time, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  tq_time_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("110 seconds"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("95 Seconds"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("80 Seconds"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("70 Seconds"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("60 Seconds"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("45 Seconds"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("30 Seconds"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Free Play"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_time_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (tq_time), tq_time_menu);

  tq_cost = gtk_option_menu_new ();
  gtk_widget_ref (tq_cost);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_cost", tq_cost,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_cost);
  gtk_table_attach (GTK_TABLE (table3), tq_cost, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  tq_cost_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("One coin"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Two coins"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_cost_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (tq_cost), tq_cost_menu);

  tq_audio = gtk_option_menu_new ();
  gtk_widget_ref (tq_audio);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_audio", tq_audio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_audio);
  gtk_table_attach (GTK_TABLE (table3), tq_audio, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  tq_audio_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Plays one out of eight times"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_audio_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Always on"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_audio_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Always off"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_audio_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (tq_audio), tq_audio_menu);

  label22 = gtk_label_new (_("Lives"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table3), label22, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  tq_lives = gtk_option_menu_new ();
  gtk_widget_ref (tq_lives);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_lives", tq_lives,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_lives);
  gtk_table_attach (GTK_TABLE (table3), tq_lives, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  tq_lives_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Three"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Five"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_lives_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (tq_lives), tq_lives_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (tq_lives), 1);

  label17 = gtk_label_new (_("ROM names"));
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table3), label17, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  tq_rom_names = gtk_label_new (_("name1.bin, name2.bin"));
  gtk_widget_ref (tq_rom_names);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_rom_names", tq_rom_names,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_rom_names);
  gtk_table_attach (GTK_TABLE (table3), tq_rom_names, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (tq_rom_names), 0, 0.5);

  label24 = gtk_label_new (_("External Scoreboard"));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table3), label24, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  tq_scoreboard = gtk_option_menu_new ();
  gtk_widget_ref (tq_scoreboard);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_scoreboard", tq_scoreboard,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_scoreboard);
  gtk_table_attach (GTK_TABLE (table3), tq_scoreboard, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  tq_scoreboard_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("None"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_scoreboard_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("LPT1"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_scoreboard_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("LPT2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (tq_scoreboard_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (tq_scoreboard), tq_scoreboard_menu);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator4);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "hseparator4", hseparator4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox6), hseparator4, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox12);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "hbox12", hbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox12, TRUE, TRUE, 0);

  tq_ok = gtk_button_new_with_label ("");
  tq_ok_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (tq_ok)->child),
                                   _("_OK"));
  gtk_widget_add_accelerator (tq_ok, "clicked", accel_group,
                              tq_ok_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (tq_ok);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_ok", tq_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_ok);
  gtk_box_pack_start (GTK_BOX (hbox12), tq_ok, FALSE, TRUE, 0);

  tq_cancel = gtk_button_new_with_label ("");
  tq_cancel_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (tq_cancel)->child),
                                   _("_Cancel"));
  gtk_widget_add_accelerator (tq_cancel, "clicked", accel_group,
                              tq_cancel_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (tq_cancel);
  gtk_object_set_data_full (GTK_OBJECT (tq_window), "tq_cancel", tq_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tq_cancel);
  gtk_box_pack_start (GTK_BOX (hbox12), tq_cancel, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (tq_window), "destroy",
                      GTK_SIGNAL_FUNC (on_tq_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (tq_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_tq_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (tq_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_tq_cancel_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (tq_window), accel_group);

  return tq_window;
}

GtkWidget*
create_sdq_window (void)
{
  GtkWidget *sdq_window;
  GtkWidget *vbox7;
  GtkWidget *label32;
  GtkWidget *hseparator7;
  GtkWidget *table4;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label25;
  GtkWidget *sdq_rom_names;
  GtkWidget *sdq_lives;
  GtkWidget *sdq_lives_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *sdq_difficulty;
  GtkWidget *sdq_difficulty_menu;
  GtkWidget *sdq_audio;
  GtkWidget *sdq_audio_menu;
  GtkWidget *sdq_cost;
  GtkWidget *sdq_cost_menu;
  GtkWidget *sdq_extra_life;
  GtkWidget *sdq_extra_life_menu;
  GtkWidget *hseparator6;
  GtkWidget *hbox13;
  guint sdq_ok_key;
  GtkWidget *sdq_ok;
  guint sdq_cancel_key;
  GtkWidget *sdq_cancel;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  sdq_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (sdq_window), "sdq_window", sdq_window);
  gtk_window_set_title (GTK_WINDOW (sdq_window), _("Super Don Configuration"));

  vbox7 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (sdq_window), vbox7);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 10);

  label32 = gtk_label_new (_("Description: Super Don Quix-ote, UNIVERSAL's finest!!!"));
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (vbox7), label32, FALSE, FALSE, 0);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator7);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "hseparator7", hseparator7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator7);
  gtk_box_pack_start (GTK_BOX (vbox7), hseparator7, TRUE, TRUE, 0);

  table4 = gtk_table_new (6, 2, TRUE);
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox7), table4, TRUE, TRUE, 0);

  label26 = gtk_label_new (_("Lives"));
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table4), label26, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  label27 = gtk_label_new (_("Difficulty"));
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table4), label27, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("Attract mode audio"));
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table4), label28, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("Cost to play"));
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table4), label29, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("Extra life"));
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table4), label30, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label25 = gtk_label_new (_("ROM names"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table4), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  sdq_rom_names = gtk_label_new (_("name1.bin, name2.bin, name3.bin"));
  gtk_widget_ref (sdq_rom_names);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_rom_names", sdq_rom_names,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_rom_names);
  gtk_table_attach (GTK_TABLE (table4), sdq_rom_names, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (sdq_rom_names), 0, 0.5);

  sdq_lives = gtk_option_menu_new ();
  gtk_widget_ref (sdq_lives);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_lives", sdq_lives,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_lives);
  gtk_table_attach (GTK_TABLE (table4), sdq_lives, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  sdq_lives_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Two"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Three"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Four"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Five"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Unlimited"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_lives_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (sdq_lives), sdq_lives_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (sdq_lives), 3);

  sdq_difficulty = gtk_option_menu_new ();
  gtk_widget_ref (sdq_difficulty);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_difficulty", sdq_difficulty,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_difficulty);
  gtk_table_attach (GTK_TABLE (table4), sdq_difficulty, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  sdq_difficulty_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Easy"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Normal"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Harder"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Difficult"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_difficulty_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (sdq_difficulty), sdq_difficulty_menu);

  sdq_audio = gtk_option_menu_new ();
  gtk_widget_ref (sdq_audio);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_audio", sdq_audio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_audio);
  gtk_table_attach (GTK_TABLE (table4), sdq_audio, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  sdq_audio_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Always On"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_audio_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Always Off"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_audio_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (sdq_audio), sdq_audio_menu);

  sdq_cost = gtk_option_menu_new ();
  gtk_widget_ref (sdq_cost);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_cost", sdq_cost,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_cost);
  gtk_table_attach (GTK_TABLE (table4), sdq_cost, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  sdq_cost_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("1 coin, 1 credit"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("1 coin, 2 credits"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("1 coin, 3 credits"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("2 coins, 1 credit"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Free Play"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_cost_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (sdq_cost), sdq_cost_menu);

  sdq_extra_life = gtk_option_menu_new ();
  gtk_widget_ref (sdq_extra_life);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_extra_life", sdq_extra_life,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_extra_life);
  gtk_table_attach (GTK_TABLE (table4), sdq_extra_life, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  sdq_extra_life_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("One per 100,000 points"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_extra_life_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("No extra life"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (sdq_extra_life_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (sdq_extra_life), sdq_extra_life_menu);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator6);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "hseparator6", hseparator6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (vbox7), hseparator6, TRUE, TRUE, 0);

  hbox13 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox13);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox13, TRUE, TRUE, 0);

  sdq_ok = gtk_button_new_with_label ("");
  sdq_ok_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (sdq_ok)->child),
                                   _("_OK"));
  gtk_widget_add_accelerator (sdq_ok, "clicked", accel_group,
                              sdq_ok_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (sdq_ok);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_ok", sdq_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_ok);
  gtk_box_pack_start (GTK_BOX (hbox13), sdq_ok, FALSE, TRUE, 0);

  sdq_cancel = gtk_button_new_with_label ("");
  sdq_cancel_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (sdq_cancel)->child),
                                   _("_Cancel"));
  gtk_widget_add_accelerator (sdq_cancel, "clicked", accel_group,
                              sdq_cancel_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (sdq_cancel);
  gtk_object_set_data_full (GTK_OBJECT (sdq_window), "sdq_cancel", sdq_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (sdq_cancel);
  gtk_box_pack_start (GTK_BOX (hbox13), sdq_cancel, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (sdq_window), "destroy",
                      GTK_SIGNAL_FUNC (on_sdq_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (sdq_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_sdq_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (sdq_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_sdq_cancel_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (sdq_window), accel_group);

  return sdq_window;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *file_ok_button1;
  GtkWidget *file_cancel_button1;

  fileselection1 = gtk_file_selection_new (_("Select File"));
  gtk_object_set_data (GTK_OBJECT (fileselection1), "fileselection1", fileselection1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);

  file_ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "file_ok_button1", file_ok_button1);
  gtk_widget_show (file_ok_button1);
  GTK_WIDGET_SET_FLAGS (file_ok_button1, GTK_CAN_DEFAULT);

  file_cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_object_set_data (GTK_OBJECT (fileselection1), "file_cancel_button1", file_cancel_button1);
  gtk_widget_show (file_cancel_button1);
  GTK_WIDGET_SET_FLAGS (file_cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (fileselection1), "destroy",
                      GTK_SIGNAL_FUNC (on_fileselection1_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file_ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_file_ok_button1_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file_cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (on_file_cancel_button1_clicked),
                      NULL);

  return fileselection1;
}

GtkWidget*
create_cliff_window (void)
{
  GtkWidget *cliff_window;
  GtkWidget *vbox8;
  GtkWidget *label45;
  GtkWidget *hseparator8;
  GtkWidget *table5;
  GtkWidget *cliff_rom_names;
  GtkWidget *label33;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *cliff_difficulty;
  GtkWidget *cliff_difficulty_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *cliff_cost;
  GtkWidget *cliff_cost_menu;
  GtkWidget *cliff_lives;
  GtkWidget *cliff_lives_menu;
  GtkWidget *cliff_audio;
  GtkWidget *cliff_audio_menu;
  GtkWidget *cliff_scene_length;
  GtkWidget *cliff_scene_length_menu;
  GtkWidget *cliff_buy_in;
  GtkWidget *cliff_buy_in_menu;
  GtkWidget *cliff_hanging_scene;
  GtkWidget *cliff_hanging_scene_menu;
  GtkWidget *cliff_overlay;
  GtkWidget *cliff_overlay_menu;
  GtkWidget *cliff_action_stick;
  GtkWidget *cliff_action_stick_menu;
  GtkWidget *label39;
  GtkWidget *label44;
  GtkWidget *cliff_hints;
  GtkWidget *cliff_hints_menu;
  GtkWidget *hseparator9;
  GtkWidget *hbox14;
  guint cliff_ok_key;
  GtkWidget *cliff_ok;
  guint cliff_cancel_key;
  GtkWidget *cliff_cancel;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  cliff_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (cliff_window), "cliff_window", cliff_window);
  gtk_container_set_border_width (GTK_CONTAINER (cliff_window), 10);
  gtk_window_set_title (GTK_WINDOW (cliff_window), _("Cliff Hanger Configuration"));

  vbox8 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (cliff_window), vbox8);

  label45 = gtk_label_new (_("Description: Cliff Hanger, a game that keeps you on the edge of your toes"));
  gtk_widget_ref (label45);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label45", label45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (vbox8), label45, FALSE, FALSE, 0);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator8);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "hseparator8", hseparator8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator8, TRUE, TRUE, 0);

  table5 = gtk_table_new (11, 2, TRUE);
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (vbox8), table5, TRUE, TRUE, 0);

  cliff_rom_names = gtk_label_new (_("name1.bin, name2.bin, etc"));
  gtk_widget_ref (cliff_rom_names);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_rom_names", cliff_rom_names,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_rom_names);
  gtk_table_attach (GTK_TABLE (table5), cliff_rom_names, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (cliff_rom_names), 0, 0.5);

  label33 = gtk_label_new (_("ROM names"));
  gtk_widget_ref (label33);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label33", label33,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table5), label33, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  label35 = gtk_label_new (_("Difficulty"));
  gtk_widget_ref (label35);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label35", label35,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label35);
  gtk_table_attach (GTK_TABLE (table5), label35, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label35), 0, 0.5);

  label36 = gtk_label_new (_("Coins per credit"));
  gtk_widget_ref (label36);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label36", label36,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table5), label36, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  label37 = gtk_label_new (_("Lives"));
  gtk_widget_ref (label37);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label37", label37,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table5), label37, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label38 = gtk_label_new (_("Attract mode audio"));
  gtk_widget_ref (label38);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label38", label38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table5), label38, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label40 = gtk_label_new (_("\"Buy in\" feature?"));
  gtk_widget_ref (label40);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label40", label40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table5), label40, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);

  label41 = gtk_label_new (_("Hanging Scene"));
  gtk_widget_ref (label41);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label41", label41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table5), label41, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label42 = gtk_label_new (_("Score & Remaining Lives"));
  gtk_widget_ref (label42);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label42", label42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table5), label42, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new (_("ACTION/STICK Hints"));
  gtk_widget_ref (label43);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label43", label43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table5), label43, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  cliff_difficulty = gtk_option_menu_new ();
  gtk_widget_ref (cliff_difficulty);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_difficulty", cliff_difficulty,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_difficulty);
  gtk_table_attach (GTK_TABLE (table5), cliff_difficulty, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  cliff_difficulty_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("1 - Easiest"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("3"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("4"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("5"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("6"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("7"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("8"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("9"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("10"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("11"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("12"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("13"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("14"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("15"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("16 - Hardest"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_difficulty_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_difficulty), cliff_difficulty_menu);

  cliff_cost = gtk_option_menu_new ();
  gtk_widget_ref (cliff_cost);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_cost", cliff_cost,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_cost);
  gtk_table_attach (GTK_TABLE (table5), cliff_cost, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  cliff_cost_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("One Coin"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Two Coins"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Three Coins"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Four Coins"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_cost_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Free Play"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_cost_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_cost), cliff_cost_menu);

  cliff_lives = gtk_option_menu_new ();
  gtk_widget_ref (cliff_lives);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_lives", cliff_lives,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_lives);
  gtk_table_attach (GTK_TABLE (table5), cliff_lives, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  cliff_lives_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Three"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Four"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Five"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Six"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_lives_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Unlimited"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_lives_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_lives), cliff_lives_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (cliff_lives), 3);

  cliff_audio = gtk_option_menu_new ();
  gtk_widget_ref (cliff_audio);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_audio", cliff_audio,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_audio);
  gtk_table_attach (GTK_TABLE (table5), cliff_audio, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  cliff_audio_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Always on"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_audio_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Always off"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_audio_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_audio), cliff_audio_menu);

  cliff_scene_length = gtk_option_menu_new ();
  gtk_widget_ref (cliff_scene_length);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_scene_length", cliff_scene_length,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_scene_length);
  gtk_table_attach (GTK_TABLE (table5), cliff_scene_length, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, cliff_scene_length, _("Cliff Hanger can shorten some scenes where no action is happening."), NULL);
  cliff_scene_length_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Full"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_scene_length_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Shortened"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_scene_length_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_scene_length), cliff_scene_length_menu);

  cliff_buy_in = gtk_option_menu_new ();
  gtk_widget_ref (cliff_buy_in);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_buy_in", cliff_buy_in,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_buy_in);
  gtk_table_attach (GTK_TABLE (table5), cliff_buy_in, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  cliff_buy_in_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Enabled"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_buy_in_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Disabled"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_buy_in_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_buy_in), cliff_buy_in_menu);

  cliff_hanging_scene = gtk_option_menu_new ();
  gtk_widget_ref (cliff_hanging_scene);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_hanging_scene", cliff_hanging_scene,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_hanging_scene);
  gtk_table_attach (GTK_TABLE (table5), cliff_hanging_scene, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, cliff_hanging_scene, _("After every death, a scene of Cliff hanging from a noose can be displayed.  The hanging scene gets old really quick."), NULL);
  cliff_hanging_scene_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Shown after every death"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_hanging_scene_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Never shown"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_hanging_scene_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_hanging_scene), cliff_hanging_scene_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (cliff_hanging_scene), 1);

  cliff_overlay = gtk_option_menu_new ();
  gtk_widget_ref (cliff_overlay);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_overlay", cliff_overlay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_overlay);
  gtk_table_attach (GTK_TABLE (table5), cliff_overlay, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, cliff_overlay, _("Cliff Hanger can overlay the current score and number of remaining lives on top of the animation."), NULL);
  cliff_overlay_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Always shown"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_overlay_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Not shown during gameplay"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_overlay_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_overlay), cliff_overlay_menu);

  cliff_action_stick = gtk_option_menu_new ();
  gtk_widget_ref (cliff_action_stick);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_action_stick", cliff_action_stick,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_action_stick);
  gtk_table_attach (GTK_TABLE (table5), cliff_action_stick, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, cliff_action_stick, _("This hint tells the player whether the next move is an action button or a joystick move."), NULL);
  cliff_action_stick_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Enabled"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_action_stick_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Disabled"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_action_stick_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_action_stick), cliff_action_stick_menu);

  label39 = gtk_label_new (_("Length of scenes"));
  gtk_widget_ref (label39);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label39", label39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table5), label39, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);

  label44 = gtk_label_new (_("Hints after player dies"));
  gtk_widget_ref (label44);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "label44", label44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table5), label44, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  cliff_hints = gtk_option_menu_new ();
  gtk_widget_ref (cliff_hints);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_hints", cliff_hints,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_hints);
  gtk_table_attach (GTK_TABLE (table5), cliff_hints, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, cliff_hints, _("This hint tells the player the correct move after he has died."), NULL);
  cliff_hints_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("After every death"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_hints_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("After 2 failed attempts"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_hints_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("After 3 failed attempts"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_hints_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Never"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (cliff_hints_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (cliff_hints), cliff_hints_menu);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_ref (hseparator9);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "hseparator9", hseparator9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator9);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator9, TRUE, TRUE, 0);

  hbox14 = gtk_hbox_new (TRUE, 5);
  gtk_widget_ref (hbox14);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox14, TRUE, TRUE, 0);

  cliff_ok = gtk_button_new_with_label ("");
  cliff_ok_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (cliff_ok)->child),
                                   _("_OK"));
  gtk_widget_add_accelerator (cliff_ok, "clicked", accel_group,
                              cliff_ok_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (cliff_ok);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_ok", cliff_ok,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_ok);
  gtk_box_pack_start (GTK_BOX (hbox14), cliff_ok, FALSE, TRUE, 0);

  cliff_cancel = gtk_button_new_with_label ("");
  cliff_cancel_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (cliff_cancel)->child),
                                   _("_Cancel"));
  gtk_widget_add_accelerator (cliff_cancel, "clicked", accel_group,
                              cliff_cancel_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (cliff_cancel);
  gtk_object_set_data_full (GTK_OBJECT (cliff_window), "cliff_cancel", cliff_cancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cliff_cancel);
  gtk_box_pack_start (GTK_BOX (hbox14), cliff_cancel, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (cliff_window), "destroy",
                      GTK_SIGNAL_FUNC (on_cliff_window_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cliff_ok), "clicked",
                      GTK_SIGNAL_FUNC (on_cliff_ok_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cliff_cancel), "clicked",
                      GTK_SIGNAL_FUNC (on_cliff_cancel_clicked),
                      NULL);

  gtk_object_set_data (GTK_OBJECT (cliff_window), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (cliff_window), accel_group);

  return cliff_window;
}

GtkWidget*
create_no_config_dialog (void)
{
  GtkWidget *no_config_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *label48;
  GtkWidget *dialog_action_area1;
  guint no_config_button_key;
  GtkWidget *no_config_button;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  no_config_dialog = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (no_config_dialog), "no_config_dialog", no_config_dialog);
  gtk_container_set_border_width (GTK_CONTAINER (no_config_dialog), 10);
  gtk_window_set_title (GTK_WINDOW (no_config_dialog), _("Configuration?"));
  gtk_window_set_policy (GTK_WINDOW (no_config_dialog), FALSE, FALSE, TRUE);

  dialog_vbox1 = GTK_DIALOG (no_config_dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (no_config_dialog), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label48 = gtk_label_new (_("There is no configuration required for this choice."));
  gtk_widget_ref (label48);
  gtk_object_set_data_full (GTK_OBJECT (no_config_dialog), "label48", label48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label48, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (no_config_dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (no_config_dialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  no_config_button = gtk_button_new_with_label ("");
  no_config_button_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (no_config_button)->child),
                                   _("_OK"));
  gtk_widget_add_accelerator (no_config_button, "clicked", accel_group,
                              no_config_button_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (no_config_button);
  gtk_object_set_data_full (GTK_OBJECT (no_config_dialog), "no_config_button", no_config_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (no_config_button);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), no_config_button, FALSE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (no_config_button), "destroy",
                      GTK_SIGNAL_FUNC (on_no_config_button_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (no_config_button), "clicked",
                      GTK_SIGNAL_FUNC (on_no_config_button_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (no_config_dialog), accel_group);

  return no_config_dialog;
}

