/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#define PACKAGE_DATA_DIR "."
#define PACKAGE_SOURCE_DIR "."

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

GtkWidget *g_setup_window;
GtkWidget *g_dl_window;
GtkWidget *g_ldp_window;
GtkWidget *g_tq_window;
GtkWidget *g_sdq_window;
GtkWidget *g_fileselection1;
GtkWidget *g_cliff_window;

int
main (int argc, char *argv[])
{

#ifdef ENABLE_NLS
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");
  add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  g_setup_window = create_setup_window ();
  gtk_widget_show (g_setup_window);
//  g_dl_window = create_dl_window ();
//  g_ldp_window = create_ldp_window ();
//  g_tq_window = create_tq_window ();
//  g_sdq_window = create_sdq_window ();
//  g_fileselection1 = create_fileselection1 ();
//  g_cliff_window = create_cliff_window ();

  gtk_main ();
  return 0;
}

