name: CMake-MacOS-Brew-MPEG2

on:
 workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'MacOS (brew libmpeg2) Build'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@master
        with:
          ref: libmpeg2
      - name: Install Homebrew

        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        if: success()
      - name: Install Dependencies
        run: |
          brew install sdl2
          brew install sdl2_ttf
          brew install sdl2_image
          brew install sdl2_mixer
          brew install automake
          brew install libvorbis
          brew install libmpeg2
          brew install libzip
        if: success()
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../src
          make
      - name: Package
        run: |
          cp build/hypseus .
          cp screenshots/hypseus-logo.png hypseus.png
          FILES="hypseus LICENSE README.md hypseus.png fonts/ midi/ pics/ roms/ sound/ scripts/"
          zip -r hypseus-singe.zip $FILES
      - name: Create Distribution
        id: vars
        run: |
          ShortSHA=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$ShortSHA" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: hypseus-singe-MacOS-${{ env.COMMIT_SHORT_SHA }}
          path: hypseus-singe.zip

